#!/usr/bin/env python

"""Reads REAL ESSI .fei input file.

It reads the input file and has capability to perform 
various manipulations on it.
"""

__author__ = "Sumeet K. Sinha"
__credits__ = [""]
__license__ = "GPL"
__version__ = "2.0"
__maintainer__ = "Sumeet K. Sinha"
__email__ = "sumeet.kumar507@gmail.com"


import h5py;
import sys,cStringIO;


class ESSI_Intput:
	'It reads the .feioutput file generated by Real-ESSI Simulator'

	FeiInputFile     = None;

	def __str__(self):
		return "\
\n---------------------------------------\n\
ESSI_Intput -> %s\n---------------------------------------\n\t\
" % (self.FeiInputFile)

	def __init__ (self,inputFile):
		""" Define ESSI_Intput class with output file

		Class Variables:
		FeiInputFile -- the hdf5.feioutput filename
		"""
		self.FeiOutputFile = inputFile;
		self.__initialize();


	# def __initialize(self):
	# 	""" Initializes the variables by getting data from 
	# 	HDF5 output file
	# 	"""
	# 	# self.__MainHDF5File   = h5py.File(self.FeiOutputFile, 'r');
	# 	# self.__HDF5_File      = self.__MainHDF5File;
	# 	# self.NumTimeSteps     = self.__MainHDF5File['Number_of_Time_Steps'][0];
	# 	# self.NumProcess       = self.__MainHDF5File['Number_of_Processes_Used'][0];
	# 	# self.StageName        = self.__MainHDF5File['Stage_Name'][0];
	# 	# self.VersionInfo      = self.__MainHDF5File['Version Info'][0];
	# 	# self.PreviousStage    = self.__MainHDF5File['Previous_Stage'][0];
	# 	# self.ModelName        = self.__MainHDF5File['Model_Name'][0];
	# 	# if(self.NumProcess>1):
	# 	# 	self.__Sequential = False;
	# 	# 	self.MaxElementTag     = len(self.__MainHDF5File['Model/Elements/Partition'])-1; 
	# 	# 	self.MaxNodeTag        = len(self.__MainHDF5File['Model/Nodes/Partition'])-1; 
	# 	# 	self.OutputMode        = "Parallel";
	# 	# else:
	# 	# 	self.MaxElementTag     = len(self.__MainHDF5File['/Model/Elements/Index_to_Connectivity'])-1; 
	# 	# 	self.MaxNodeTag        = len(self.__MainHDF5File['/Model/Nodes/Index_to_Coordinates'])-1;
	# 	# 	self.OutputMode        = "Sequential";


